import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await mkdir('test-results', { recursive: true });
try {
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:3000', { waitUntil: 'networkidle' });
  await page.getByRole('heading', { name: 'สนามของเพื่อนเรา.' }).waitFor();
  assert.equal(await page.locator('.standings-table tbody tr').count(), 7);
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  for (const width of [360, 390, 430]) {
    await page.setViewportSize({ width, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `page overflow at ${width}px`);
    assert.ok(await page.locator('.bottom-nav').isVisible());
    await page.screenshot({ path: `test-results/mobile-${width}.png`, fullPage: true });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  const bottom = page.locator('.bottom-nav');
  await bottom.getByRole('button', { name: 'บันทึกผลแข่ง', exact: true }).click();
  await page.getByLabel('ผู้เล่น A', { exact: true }).selectOption({ label: 'Ta' });
  await page.getByLabel('ผู้เล่น B', { exact: true }).selectOption({ label: 'Nicky' });
  await expect(page.getByLabel('ผู้เล่น B', { exact: true }).locator('option', { hasText: 'Ta' })).toHaveJSProperty('disabled', true);
  await page.getByRole('button', { name: 'เพิ่มสกอร์ ผู้เล่น A', exact: true }).click();
  await page.getByRole('button', { name: 'เพิ่มสกอร์ ผู้เล่น A', exact: true }).click();
  await page.getByRole('button', { name: 'เพิ่มสกอร์ ผู้เล่น B', exact: true }).click();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: 'test-results/match-form.png', fullPage: true });
  await page.getByRole('button', { name: 'บันทึกผลการแข่งขัน', exact: true }).click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('button', { name: 'กลับไปแก้ไข', exact: true }).click();
  assert.equal(await page.locator('dialog[open]').count(), 0);
  await page.getByRole('button', { name: 'บันทึกผลการแข่งขัน', exact: true }).click();
  await page.getByRole('button', { name: 'ยืนยันบันทึก', exact: true }).click();
  await page.getByRole('heading', { name: 'สนามของเพื่อนเรา.' }).waitFor();
  assert.match(await page.locator('.summary-card').nth(1).innerText(), /31/);
  await page.getByRole('button', { name: 'ดูทั้งหมด', exact: true }).click();
  await page.getByRole('heading', { name: 'ผลการแข่งขัน · 31 แมตช์' }).waitFor();
  await page.getByRole('button', { name: 'แก้ไข', exact: true }).first().click();
  await page.getByLabel('สกอร์ ผู้เล่น B', { exact: true }).fill('3');
  await page.getByRole('button', { name: 'ตรวจสอบผลที่แก้ไข', exact: true }).click();
  await page.getByRole('button', { name: 'ยืนยันบันทึก', exact: true }).click();
  await page.getByRole('button', { name: 'ดูทั้งหมด', exact: true }).click();
  assert.match(await page.locator('.match-row').first().innerText(), /2\s*:\s*3/);
  await page.getByRole('button', { name: 'ลบ', exact: true }).first().click();
  await page.getByRole('button', { name: 'ยืนยันลบ', exact: true }).click();
  await page.getByRole('heading', { name: 'ผลการแข่งขัน · 30 แมตช์' }).waitFor();
  await page.getByLabel('ผู้เล่น', { exact: true }).selectOption({ label: 'Ta / Gunner' });
  for (const row of await page.locator('.match-row').all()) assert.match(await row.innerText(), /Ta/);
  await bottom.getByRole('button', { name: 'ตั้งค่า', exact: true }).click();
  await page.getByRole('button', { name: 'ลบ Ta', exact: true }).click();
  await page.getByRole('button', { name: 'ยืนยันลบ', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('ผู้เล่นนี้มีผลการแข่งขันแล้ว');
  await page.getByRole('dialog').getByRole('button', { name: 'ยกเลิก', exact: true }).click();
  await page.getByRole('button', { name: 'เพิ่มผู้เล่น', exact: true }).click();
  await page.getByLabel('ชื่อผู้เล่น', { exact: true }).fill('Tester');
  await page.getByLabel('ชื่อทีม', { exact: true }).fill('Test United');
  await page.getByRole('button', { name: 'บันทึกผู้เล่น', exact: true }).click();
  await page.getByRole('button', { name: 'แก้ไข Tester', exact: true }).click();
  await page.getByLabel('ชื่อทีม', { exact: true }).fill('Test FC');
  await page.getByRole('button', { name: 'บันทึกผู้เล่น', exact: true }).click();
  assert.ok(await page.getByText('Test FC', { exact: true }).isVisible());
  await page.getByRole('button', { name: 'ลบ Tester', exact: true }).click();
  await page.getByRole('button', { name: 'ยืนยันลบ', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'ลบ Tester', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'สร้างฤดูกาล', exact: true }).click();
  await page.getByLabel('ชื่อฤดูกาล', { exact: true }).fill('FA League 21');
  await page.getByRole('dialog').getByRole('button', { name: 'สร้างฤดูกาล', exact: true }).click();
  await page.getByRole('button', { name: 'ใช้ฤดูกาลนี้', exact: true }).click();
  assert.equal(await page.getByLabel('เลือกฤดูกาล', { exact: true }).inputValue(), await page.locator('.season-select option').filter({ hasText: 'FA League 21' }).getAttribute('value'));
  await bottom.getByRole('button', { name: 'บันทึกผลแข่ง', exact: true }).click();
  await page.getByText('ต้องมีผู้เล่นอย่างน้อย 2 คนในฤดูกาลนี้ ให้ผู้ดูแลเพิ่มผู้เล่นในหน้าตั้งค่า').waitFor();
  await page.reload({ waitUntil: 'networkidle' });
  assert.match(await page.locator('.summary-card').nth(1).innerText(), /30/);
  await bottom.getByRole('button', { name: 'สถิติผู้เล่น', exact: true }).click();
  await page.locator('.player-card').first().click();
  assert.equal(await page.locator('.detail-stats>div').count(), 8);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog[open]').count(), 0);
  assert.deepEqual(errors, [], 'browser errors');
  console.log('Browser checks passed: desktop + 360/390/430px, add/confirm/edit/delete matches, filtering, player CRUD, season creation/activation, player details and demo reset.');
} finally { await browser.close(); }
